import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

const CommonStyles = StyleSheet.create({
  // Common styles
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
    marginTop: 12,
    fontFamily: "Roboto",
  },
  errorText: {
    color: "#ff4444",
    fontSize: 16,
    textAlign: "center",
    marginTop: 20,
    fontFamily: "Roboto",
  },
  retryButton: {
    backgroundColor: "#F97316",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  retryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Roboto",
  },
  sectionTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 10,
    paddingTop: 4,
    fontFamily: "Roboto",
  },

  // MainHome-specific styles
  mainHome: {
    sliderContainer: {
      marginBottom: 20,
      position: "relative",
    },
    sliderImage: {
      width: width,
      height: width * 0.56,
      backgroundColor: "#111",
    },
    sliderOverlay: {
      position: "absolute",
      bottom: 30,
      left: 16,
      right: 16,
      alignItems: "center",
    },
    navButton: {
      position: "absolute",
      top: "50%",
      transform: [{ translateY: -20 }],
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      borderRadius: 20,
      padding: 10,
    },
    prevButton: {
      left: 16,
    },
    nextButton: {
      right: 16,
    },
    buttonContainer: {
      flexDirection: "row",
      alignItems: "center",
    },
    subscribeButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#FF6F00",
      borderRadius: 50,
      paddingHorizontal: 16,
      paddingVertical: 10,
      marginRight: 12,
      elevation: 4,
    },
    subscribeText: {
      marginLeft: 8,
      color: "#fff",
      fontWeight: "700",
      fontSize: 16,
    },
    shareButton: {
      backgroundColor: "#e50914",
      borderRadius: 50,
      padding: 10,
      elevation: 4,
    },
    sectionContainer: {
      marginVertical: 12,
      paddingHorizontal: 12,
    },
    card: {
      marginRight: 12,
      width: 128,
    },
    cardImage: {
      width: "100%",
      height: 200,
      borderRadius: 10,
      backgroundColor: "#222",
    },
    cardTitle: {
      color: "#fff",
      fontWeight: "600",
      marginTop: 6,
      fontSize: 14,
    },
    cardAuthor: {
      color: "#aaa",
      fontSize: 12,
    },
  },

  // ViewDetails-specific styles
  viewDetails: {
    scrollContent: {
      padding: 16,
      alignItems: "center",
      flexGrow: 1,
      backgroundColor: "#000",
      paddingBottom: 80,
    },
    backButton: {
      position: "absolute",
      top: 10,
      left: 10,
      backgroundColor: "rgba(0,0,0,0.7)",
      padding: 8,
      borderRadius: 20,
      zIndex: 1,
      elevation: 2,
    },
    posterWrapper: {
      width: width - 32,
      height: (width - 32) * (9 / 16),
      borderRadius: 12,
      overflow: "hidden",
      marginBottom: 20,
      marginTop: 20,
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
    },
    poster: {
      width: "100%",
      height: "100%",
    },
    videoContainer: {
      width: width - 32,
      height: (width - 32) * (9 / 16),
      backgroundColor: "#000",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 12,
      overflow: "hidden",
    },
    video: {
      width: "100%",
      height: "100%",
    },
    playOverlay: {
      position: "absolute",
      backgroundColor: "rgba(245, 124, 0, 0.7)",
      borderRadius: 50,
      padding: 15,
    },
    speedControls: {
      position: "absolute",
      bottom: 10,
      flexDirection: "row",
      justifyContent: "space-around",
      width: "100%",
      paddingHorizontal: 20,
    },
    speedButton: {
      color: "#fff",
      backgroundColor: "rgba(0,0,0,0.7)",
      padding: 8,
      borderRadius: 20,
      fontSize: 14,
    },
    title: {
      color: "#fff",
      fontSize: 26,
      fontWeight: "700",
      textAlign: "center",
      marginBottom: 8,
      fontFamily: "Roboto",
    },
    subtitle: {
      color: "#9CA3AF",
      fontSize: 14,
      textAlign: "center",
      fontFamily: "Roboto",
    },
    badges: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 10,
      gap: 12,
    },
    rating: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#1F2937",
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
    },
    ratingText: {
      color: "#fff",
      marginLeft: 6,
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Roboto",
    },
    ageBadge: {
      backgroundColor: "#1F2937",
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
    },
    ageText: {
      color: "#fff",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Roboto",
    },
    buttonColumn: {
      marginTop: 16,
      width: "100%",
      alignItems: "center",
      gap: 12,
    },
    playButton: {
      backgroundColor: "#F97316",
      paddingVertical: 12,
      paddingHorizontal: 60,
      borderRadius: 30,
      alignItems: "center",
      width: "80%",
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    trailerButton: {
      backgroundColor: "#1F2937",
      paddingVertical: 12,
      paddingHorizontal: 60,
      borderRadius: 30,
      alignItems: "center",
      width: "80%",
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    infoButton: {
      backgroundColor: "#1F2937",
      paddingVertical: 12,
      paddingHorizontal: 40,
      borderRadius: 30,
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
      width: "80%",
      justifyContent: "center",
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    playButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "700",
      fontFamily: "Roboto",
    },
    trailerButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "700",
      fontFamily: "Roboto",
    },
    infoButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "700",
      fontFamily: "Roboto",
    },
    actions: {
      flexDirection: "row",
      justifyContent: "space-around",
      marginTop: 20,
      width: "100%",
    },
    actionItem: {
      alignItems: "center",
    },
    actionText: {
      color: "#fff",
      fontSize: 12,
      marginTop: 6,
      fontFamily: "Roboto",
    },
    description: {
      color: "#D1D5DB",
      fontSize: 14,
      marginTop: 16,
      textAlign: "left",
      lineHeight: 20,
      fontFamily: "Roboto",
    },
    extraInfo: {
      color: "#9CA3AF",
      fontSize: 13,
      marginTop: 8,
      width: "100%",
      fontFamily: "Roboto",
    },
    bold: {
      fontWeight: "700",
      color: "#fff",
      fontFamily: "Roboto",
    },
    tabBar: {
      flexDirection: "row",
      marginTop: 20,
      backgroundColor: "#1F2937",
      borderRadius: 30,
      overflow: "hidden",
      width: "100%",
    },
    tabButton: {
      flex: 1,
      paddingVertical: 12,
      alignItems: "center",
    },
    activeTab: {
      backgroundColor: "#F97316",
    },
    tabText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "600",
      fontFamily: "Roboto",
    },
    activeTabText: {
      color: "#000",
      fontFamily: "Roboto",
    },
    episodeSection: {
      marginTop: 20,
      width: "100%",
    },
    infoSection: {
      marginTop: 20,
      width: "100%",
    },
    episodeList: {
      paddingBottom: 16,
    },
    castList: {
      paddingBottom: 16,
    },
    episodeCard: {
      width: width - 32,
      marginBottom: 12,
      backgroundColor: "#1F2937",
      borderRadius: 8,
      overflow: "hidden",
      elevation: 3,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    episodeThumbnail: {
      width: "100%",
      height: 180,
    },
    episodeInfo: {
      padding: 10,
    },
    episodeNumber: {
      color: "#F97316",
      fontSize: 14,
      fontWeight: "600",
      fontFamily: "Roboto",
    },
    episodeTitle: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "600",
      marginTop: 4,
      fontFamily: "Roboto",
    },
    episodeDuration: {
      color: "#9CA3AF",
      fontSize: 12,
      marginTop: 4,
      fontFamily: "Roboto",
    },
    episodeDescription: {
      color: "#D1D5DB",
      fontSize: 12,
      marginTop: 4,
      lineHeight: 16,
      fontFamily: "Roboto",
    },
    castCard: {
      width: 120,
      marginRight: 12,
      alignItems: "center",
    },
    castImage: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: "#222",
    },
    castInfo: {
      alignItems: "center",
      marginTop: 8,
    },
    castName: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "600",
      fontFamily: "Roboto",
    },
    castRole: {
      color: "#9CA3AF",
      fontSize: 12,
      fontFamily: "Roboto",
    },
    noDataText: {
      color: "#9CA3AF",
      fontSize: 14,
      marginTop: 20,
      textAlign: "center",
      fontFamily: "Roboto",
    },
    modalContainer: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.9)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      width: width - 40,
      backgroundColor: "#1F2937",
      borderRadius: 12,
      padding: 20,
      alignItems: "center",
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
    },
    closeModalButton: {
      position: "absolute",
      top: 10,
      right: 10,
      padding: 8,
    },
    modalPoster: {
      width: "100%",
      height: (width - 40) * (9 / 16),
      borderRadius: 8,
      marginBottom: 16,
    },
    modalTitle: {
      color: "#fff",
      fontSize: 22,
      fontWeight: "700",
      textAlign: "center",
      marginBottom: 8,
      fontFamily: "Roboto",
    },
    modalSubtitle: {
      color: "#9CA3AF",
      fontSize: 14,
      textAlign: "center",
      marginBottom: 12,
      fontFamily: "Roboto",
    },
    modalDescription: {
      color: "#D1D5DB",
      fontSize: 14,
      textAlign: "left",
      lineHeight: 20,
      marginBottom: 16,
      fontFamily: "Roboto",
    },
    modalExtraInfo: {
      color: "#9CA3AF",
      fontSize: 13,
      marginTop: 8,
      width: "100%",
      fontFamily: "Roboto",
    },
    modalPlayButton: {
      backgroundColor: "#F97316",
      paddingVertical: 12,
      paddingHorizontal: 40,
      borderRadius: 30,
      alignItems: "center",
      marginTop: 16,
      width: "100%",
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    modalPlayButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "700",
      fontFamily: "Roboto",
    },
  },
});

export default CommonStyles;